/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package memorycompiler;

import java.util.List;
import java.util.Map;

import eu.mihosoft.jcompiler.CompiledClass;
import eu.mihosoft.jcompiler.JCompiler;

public class App {

    public static void main(String[] args) throws Exception {

        JCompiler compiler = JCompiler.newInstance();

        compiler.addSource("MyClass1", "public interface MyClass1 {}; interface MyClass2 {}");
        compiler.addSource("MyClass3", "interface MyClass3 {}; interface MyClass4 {}");

        Map<String, List<CompiledClass>> modelClasses = compiler.compileAll();

        for(String compilationUnit : modelClasses.keySet()) {
            System.out.println("> compilation unit: " + compilationUnit);
            List<CompiledClass> classes = modelClasses.get(compilationUnit);
            for(CompiledClass cls : classes) {
                System.out.println("> out: " + cls.loadClass().getName());
            }
        }

    }
}
