/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package memorycompiler;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.mdkt.compiler.InMemoryJavaCompiler;

public class App {

    public static void main(String[] args) throws Exception {

        InMemoryJavaCompiler compiler = InMemoryJavaCompiler.newInstance();

        compiler.addSource("MyClass", "public interface MyClass {}; interface MyClass2 {}");
        compiler.addSource("mcl2", "interface MyClass3 {}; interface MyClass4 {}");

        Map<String, List<Class<?>>> modelClasses;
        // modelClasses = 
        compiler.compileAll();
        // List<Class<?>> classes = modelClasses.values().stream().flatMap(cls->cls.stream()).collect(Collectors.toList());

        // for(Class<?> cls : classes) {
        //     System.out.println("> out: " + cls.getName());
        // }

    }
}
